version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: medusa_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa
    ports:
      - "5466:5432"

  redis:
    image: redis:7
    container_name: medusa_redis
